### ISSUE TITLE
Unit tests fail

### ISSUE THREAD

**Issue by arthus701** [b45ch1/algopy#55]
Hi!
I'm trying to bring algopy over to [nixpkgs](https://search.nixos.org/packages).

However, there seems to be an issue with the unit tests. Numpy moved its decorators to `numpy.testing._private.decorators`, so that I get some `ModuleNotFoundError`s and some `AttributeError`s.

I will for now only test whether importing `algopy` works, but a fix for the unit tests would be greatly appreciated!

**Comment by b45ch1** [comment]
Hello @arthus701 

I don't have the capacity for refactoring the code. I'd be happy to receive a PR, though.

**Comment by arthus701** [comment]
Hi,
I started working on it. Using the updated NumPy API was straightforward, however meanwhile also some hyperbolic functions have been removed from scipy.special. Do you have a plan what to do with the parts of your package that depend on those functions?

Cheers,
Arthus
